environment:
  NODEJS_VERSION: "10"

platform:
  - x64
  - x86

install:
  - ps: Install-Product node $env:NODEJS_VERSION $env:Platform
  - npm --msvs_version=2015 install
  - npm install

build: off

branches:
  only:
    - master
    - /^v.*$/

test_script:
  - node --version
  - npm --version
  - ps: Write-Host $env:SPELLCHECKER_PREFER_HUNSPELL


deploy_script: IF "%APPVEYOR_REPO_TAG%" == "true" (npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%)